### ISSUE TITLE
ASPA object MUST NOT allow the customer AS in the provider AS list

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill#1058]
As reported by Jay Borkenhagen ASPA objects MUST NOT allow the customer AS in the provider AS list.

We will disallow the use of customer AS as a provider in new and updated ASPAs. There are only a handful of ASPA objects in the wild, so we will ask users to update and remove the customer AS from their provider sets if/where applicable. This way, we do not need potentially complicated migration code to fix existing config.

**Comment by jayb-github** [comment]
I finally found where such an ASPA is specifically disallowed:

https://www.ietf.org/archive/id/draft-ietf-sidrops-aspa-profile-13.html#section-3.3
