### ISSUE TITLE
We cannot use embedded Trust Anchor "ta" in ver 0.13.0

### ISSUE THREAD

**Issue by yushoyamaguchi** [NLnetLabs/krill#1068]
We cannot use embedded Trust Anchor "ta" in ver 0.13.0.
However, the name "ta" is reserved name.
Is this change intentional?
.....................................................................................

![Screenshot from 2023-05-27 23-36-50](https://github.com/NLnetLabs/krill/assets/50731798/7583f8f4-41cc-400d-9033-971ae3fa829d)
![Screenshot from 2023-05-27 23-36-36](https://github.com/NLnetLabs/krill/assets/50731798/036f4bbf-f690-4af3-abc3-de451cdd2dee)

**Comment by timbru** [comment]
Apologies, I should have made this more clear in the release notes.

The TA support has had a big overhaul - we hope (and aimed) for the better. If you want to set up a TA manually, then please follow these steps:

https://krill.docs.nlnetlabs.nl/en/stable/trust-anchor.html

However, you may want to set up a testbed instead. If you run krill in testbed mode, then it will create and manage a TA for you automatically - and create a CA called 'testbed' under that TA. You can then set up your own child CAs under that testbed CA. This guide should work for that:

https://krill.docs.nlnetlabs.nl/en/stable/testbed.html

Please let me know if you run into any issues. I will close this issue for now, but feel free to re-open if you run into anything.

**Comment by yushoyamaguchi** [comment]
Thank, you.
I could use the CA  "testbed" .
