### ISSUE TITLE
v0.13.0 UI not showing all CAs

### ISSUE THREAD

**Issue by vytautaskitovas** [NLnetLabs/krill#1071]
v0.13.0. No scroll bar and CAs' IDs will not fit into drop-down list:
https://images.ipxo.com/images/2023/05/31/GvlVGKvPIW.png
Chrome, edge, fx

**Comment by timbru** [comment]
Indeed. This is not browser specific. We're working on a solution.

As a work around you can edit the URL manually:
```
http://yourhost/ui/cas/<your-ca>
```

**Comment by timbru** [comment]
fixed in release 0.13.1
