### ISSUE TITLE
AS0 RoA no delete icon when there is another existing announcement

### ISSUE THREAD

**Issue by vytautaskitovas** [NLnetLabs/krill#1109]
Krill v13.1. Having an active subnet announcement on one ASN (no RoA) and creating RoA to AS0 Krill UI shows no delete icon.
Example: Subnet x.x.x.0/24 is announced on ASxxxx (no RoA records exist for this announcement)
Created RoA AS0 for subnet x.x.x.0/24-24 (cli shows "x.x.x.0/24-24 => 0 # ") to restrict existing announcement
Krill UI shows no delete icon for "x.x.x.0/24-24 => 0 # "
![2](https://github.com/NLnetLabs/krill/assets/38241840/f9461163-22b5-4419-95d0-aa115b11c4e7)

In contrast, when both RoA records (AS0 and ASxxxx) exist, the delete icons are correctly available in the UI, as demonstrated in the provided screenshot.
![1](https://github.com/NLnetLabs/krill/assets/38241840/74e6e62b-ceb8-4087-9128-ea3fc0a1e3ea)

This problem has been observed across multiple instances with different subnets.

The issue is submitted suspecting this might be a bug,

**Comment by timbru** [comment]
This was merged into the 0.14.0 release candidate branch and will be part of 0.14.0. In addition, I found that the disallowed announcement was shown - in earlier Krill versions (<0.13), these announcements were not shown - you need to look at the details of your AS0 instead if you want to see which seen announcements are disallowed by it. This now works as before as well.
