### ISSUE TITLE
Krill should not freeze if lockfiles were not deleted properly.

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill#1171]
The `kvx` library deletes lock files on `Drop`, but this may not work if the server crashes.

**Comment by ximon18** [comment]
This issue affects Krill versions v0.14.0-v0.14.2.

This issue manifests itself as Krill running but not responding to HTTP requests or doing anything, as internally it is blocked while waiting to acquire a lock that it cannot acquire because the related lock file is unexpectedly present.
