### ISSUE TITLE
Packaging workflow is broken

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#1184]
From: https://github.com/NLnetLabs/krill/actions/workflows/pkg.yml

```
/__w/_temp/d98d7108-55b3-44a1-92ba-f2a9b1ce31af.sh: line 115: rpmlint: command not found
```

This is a known issue with Ploutos v6 which is fixed in Ploutos v7.

**Comment by partim** [comment]
This was fixed in #1193
