### ISSUE TITLE
Add support for rsync URI in the TAL instead of HTTPS for testing purposes

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#125]
### Summary
When using `use_ta = true` the generated `.tal` file contains an HTTPS URI to the `.cer` file.

Routinator is able to consume this file but OctoRPKI and Fort Validator fail unless the URI is changed to use the RSYNC protocol instead.

### Versions tested:
- Krill Docker image `nlnetlabs/krill:v0.2.0` (built from the v0.2.0 GitHub tag).
- OctoRPKI Docker image `cloudflare/octorpki` (aka `cloudflare/octorpki:latest` with digest [93131096a0a9](https://hub.docker.com/layers/cloudflare/octorpki/latest/images/sha256-93131096a0a97cb1065660b046f6003f264e79193f2e04124980cb4e1829f6b5), where `/octorpki -version` reports `OctoRPKI v1.1.4 (2019-08-06T16:51:07-0700)`.
- Fort Validator Debian package https://github.com/NICMx/FORT-validator/releases/download/v1.1.0/fort_1.1.0-1_amd64.deb installed in a Docker container using image `debian` (`Debian GNU/Linux 10 \n \l` according to `/etc/issue`), where `fort -V` reports `fort 1.1.0`.

### OctoRPKI
Error behaviour when the `.cer` URI inside the TAL file uses the HTTPS protocol:
```
octorpki      | time="2019-10-30T20:57:29Z" level=info msg="Got open https://ximontest.do.nlnetlabs.nl/ta/ta.cer: no such file or directory but repository not yet synchronized"
```
This is not a very helpful error message as the URI can definitely be fetched from inside the Docker container by WGet,

After replacing the URI inside the TAL file with an `rsync://` URI and placing the `.cer` file at that location in the RSYNC repo, OctoRPKI was then able to fetch the ROAs from Krill:
```
octorpki      | {"metadata":{"counts":2,"generated":1572476435,"valid":1572480035,"signature":"3046022100992e43910ae22e24ff252527680d21fdd749a2a12975b729466c2e59649ccfe6022100b0ea9598ed5920202aafd8a19db51878a25c3235434afcfda53dd375f42ff285","signatureDate":"3044022028a5d2aad362ed58839b188cc1de8acd9e9892739fe833ad544760482987e22002206b81de1751f504a3b0f9643c70ee0bdfa4934fe5f3db6dc411d62fb1bb2e37a2"},"roas":[{"prefix":"10.0.0.0/24","maxLength":24,"asn":"AS64496","ta":"KRILL"},{"prefix":"10.0.1.0/24","maxLength":24,"asn":"AS64496","ta":"KRILL"}]}
```

### Fort Validator
Error behaviour when the `.cer` URI inside the TAL file uses the HTTPS protocol:
```
ERR: /tmp/ta.tal: Global URI 'https://ximontest.do.nlnetlabs.nl/ta/ta.cer' does not begin with 'rsync://'.
```

After replacing the URI inside the TAL file with an `rsync://` URI and placing the `.cer` file at that location in the RSYNC repo, Fort Validator then produced a different error message:
```
ERR: rsync://ximontest.do.nlnetlabs.nl/repo/ta/0/1169977D368819F3557C6B2353ED047D0CB84192.cer: Certificate validation failed: invalid or inconsistent certificate extension
```

Ximon

**Comment by timbru** [comment]
yup, as discussed, will add support at some point in the near future..

will also create issues at those validators, because they should be updated the latest RFC on this and accept https.

**Comment by timbru** [comment]
Is this still needed? My feeling is that it isn't as validators are catching on to using https in TALs. Closing for now, but can be re-opened.
