### ISSUE TITLE
Create a docker image.

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill#15]

**Comment by ximon18** [comment]
- [/] Push Dockerfile and supporting files to GItHub: done in commit 32500c7d.
- [/] Create Krill Docker Hub repo: [done](https://cloud.docker.com/u/nlnetlabs/repository/docker/nlnetlabs/krill)
- [/] Docker Hub automatically builds when v0.1.0 is tagged: [done](https://cloud.docker.com/u/nlnetlabs/repository/registry-1.docker.io/nlnetlabs/krill/builds/426491ab-c800-4ffa-9838-93bb46f45d3a)
- [/] Added to Krill readthedocs installation instructions: [done](https://rpki.readthedocs.io/en/latest/krill/installation.html)
