### ISSUE TITLE
Allow the container TZ to be set

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#156]
It was [reported](https://eng.registro.br/pipermail/gter/2019-December/077647.html) that the Dockerized version of Krill uses the UTC time zone which in the reporters case resulted in an error communicating with a parent:

```
2019-12-16 09:58:01 [ERROR] [krill::daemon::scheduler] Error getting
updates for 'nomedaminhaCA', from parent 'nicbr_ca',  error: 'validation
error'
```

`krill` outside Docker did not have the same problem.

One possible resolution is to install the `tzdata` package and set the `TZ` environment variable, e.g.

```
  $ docker run -d --name krilltztest \
    -e TZ=Europe/Amsterdam \
    -e KRILL_AUTH_TOKEN=abc \
    -e KRILL_LOG_LEVEL=debug \
    --entrypoint=/bin/bash nlnetlabs/krill:v0.4.1 \
      -c 'apt-get install -y tzdata && krill -c /var/krill /data/krill.conf'
```

However, this could be made much easier by installing `tzdata` in the official Krill Docker image, then only TZ would need to be set.

**Comment by ximon18** [comment]
Related branch pending publication when the change to Krill is released in a new Docker image on Docker Hub: https://github.com/NLnetLabs/rpki-doc/compare/docker-krill-set-tz?expand=1

**Comment by timbru** [comment]
Was done in 0.4.2
