### ISSUE TITLE
Cannot change the rfc8183 repo back to embedded

### ISSUE THREAD

**Issue by lspgn** [NLnetLabs/krill#168]
Hello,
I have an issue, let me know what I can provide to help debugging:

Looks like I cannot change back a rfc8183 repository to embedded.
```
$ krillc repo show -c myca
Repository Details:
  type:        remote
  service uri: http://127.0.0.1:3002/rfc8181/mypub
```

The following command is giving a 400 error.
```
$ krillc repo update embedded -c myca
Status: 400 Bad Request, Error: {"code":2207,"msg":"Target repository does not allow list query."}
```

Thank you

**Comment by timbru** [comment]
Hi,

First off.. I think that you are just testing so it's fine to use 'embedded', but generally speaking users should use a repository provided by an RIR or NIR, or other party for this, unless they are really sure that they can make the repository available for everyone.

Version 0.4.1 has defaults to use an embedded repository and localhost. Very useful for testing and development, but not what you would want to use in production. Version 0.4.2 will be released next week, and it will not have the embedded repository configured for CAs by default.

Future versions will discourage the use of the embedded repository even further. Disabling the repo server by default and allowing localhost when a test flag is set only.

Having said all that...

You probably need to add your 'myca' as a publisher before you can update its repository. For this you will need to:

- generate the RFC8181 publisher request

Type `krillc repo request` and save the response

- add the publisher (as potentially remote)

`krillc publishers add --publisher myca --rfc8183 <your-file>`

- update 'myca' to use the embedded repository

`krillc repo update embedded -c myca`

So it's this final step that determines whether the CA will try remotely or embedded. But to the repository server all publisers are added as potentially remote.

**Comment by timbru** [comment]
Hi,

We have automated tests for this case, so I think it's the issue above and you removed the publisher.

But please let me know if this is still an issue. I will close this for now, but feel free to re-open.

Tim
