### ISSUE TITLE
Log the Krill version being tested by the E2E test

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#185]
I see this [in the latest Krill E2E test log](https://github.com/NLnetLabs/krill/commit/e3f768c56dfde368da298251c16bf5d39606ac18/checks?check_suite_id=414180932#step:14:131) which I cannot see how it is the Krill version being tested:

```
Pulling krill (nlnetlabs/krill:v0.4.2)...
```

However, only the Relying Party s/w versions are captured, the Krill version only appears in the logs if a test fails, not when the tests succeed.

First, let's capture the Krill s/w version as well, and see if the 0.4.2 log line occurs again and if it concurs with the captured Krill version, then decide if we actually have an issue to fix or not. I have not seen this log line with local testing or testing in the rpki-deploy repo...

**Comment by timbru** [comment]
Do you need a krill version/info API endpoint? And if so, what would be relevant info?

**Comment by ximon18** [comment]
For now I can get the version the same way I do for the RPs: `docker exec ... krill --version`.

An API endpoint would be cleaner/more robust. For end users just Krill v0.6.5 or so as a string would be enough. For GitHub E2E tests it _might_ be useful to have the actual commit hash, but you'd have to change your build process to capture that.
