### ISSUE TITLE
Replace actix-web with a simpler stack and fewer dependencies

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill#189]
We can use code from one of Martin's projects for this. Since we do not need all the features from a full fledged http server we can make do with something simpler and in the process have fewer dependencies.

**Comment by u24b6** [comment]
there is https://hyper.rs/ ; not a tremendous amount of deps: https://github.com/hyperium/hyper/blob/master/Cargo.toml#L22

**Comment by timbru** [comment]
Yes, I know. Actually, I started working on this last week.

Hyper is quite nice to use, and if you look at the code that my colleague Martin is using in a [personal project](https://github.com/railwayhistory/railsite) then it looks like we could make this do all we need with very little boilerplate.

However... I have been trying to get the hyper server to work with https and this proves to be quite challenging. What examples existed before, don't work with the recent versions of hyper, tokio and/or native_tls. Working it out from the code is not easy.

Dropping https as some people suggest (e.g. reddit) and just leaving this to a proxy is not an option. I understand and partially agree with the reasoning (e.g. nginx is just better at this, intergrates better with letsencrypt etc), this would be a regression that will not be acceptable to our user base.

I looked into using warp earlier, which is based around hyper, and which does https. But I found its routing to become complicated for our cases, and it seemed hard / impossible to make the rejection system work like we needed for our api. So, while this could work (and looks like a promising framework in general), it seemed that warp complicated, rather than simplified our code base. Still, I will have a look at how Warp manages to run a hyper server with TLS, and see what I can borrow from that.

So, there is a bit more work to do on this one.

**Comment by u24b6** [comment]
Not sure if you have noticed this: https://github.com/hyperium/hyper/issues/985

**Comment by timbru** [comment]
As a result of all this, lots and lots of stuff had to become asynchronous. This is a good thing in itself, but proved to be a lot of work. By now, the tests are green again, but there is some work remaining before this can be merged:

- [ ] Serve the static files again - so lagosta can be used here
- [ ] Clean up the test util modules - merge them into one
- [ ] Clean up: move the code in 'endpoints.rs' into 'http/server.rs'

**Comment by timbru** [comment]
> Not sure if you have noticed this: [hyperium/hyper#985](https://github.com/hyperium/hyper/issues/985)

I got things working by looking at, and adapting, how this is done in Warp.

**Comment by timbru** [comment]
merged
