### ISSUE TITLE
Create deb package and linux binaries

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill#19]
We can build a deb package, and some linux binaries, on each master build and each release.

**Comment by ximon18** [comment]
Current status (see branch `packaging`:
- DEB package file is created using `cargo deb`. The package doesn't yet have any [Debian installation scripts](https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html).
- Package is built by new GitHub Actions workflow `pkg`.
- The DEB package is built and stored as build artifact.
- A second job downloads the stored build artifact and "tests" it briefly on Ubuntu 16.04/18.04/20.04 GH runners.
- To support installation on Ubuntu 16.04, OpenSSL 1.1.0 is statically linked into the binary and an older versions of libc and libgcc that are available to 16.04 are depended on by the DEB package.
- Note: GH runners are not the best place to test as they have newer packages than stock O/S images and only Ubuntu Linux is available as a runner. Either test on VMs (but that's a bit slow and has a price) or via Docker containers e.g. that would also enable testing of various Debian versions, not just Ubuntu, and would also scale to testing an RPM build on CentOS.

**Comment by ximon18** [comment]
@timbru: As the draft PR stands the produced packages are only available to logged in GH users with sufficient rights in the project to see the artifacts on the GH action job summary page and build log pages. That would enable you to download them for testing and/or to manually attach them to a release for example. Is that sufficient?
