### ISSUE TITLE
Trying to ADD REPO

### ISSUE THREAD

**Issue by diditonf** [NLnetLabs/krill#196]
Hi,

I'm trying to ADD a repo and i'm getting this error..

root@krill:/home# krillc parents add --parent nicbr_ca --rfc8183 ./data/parent_response.xml -txxxx -c arc
Error 2100: No repository configured.

**Comment by timbru** [comment]
Hi,

The error message should be clarified. What krill is trying to tell you is that you should configure the repository for your ca before adding the parent. This workflow is documented here:

https://rpki.readthedocs.io/en/latest/krill/get-started.html#set-up-your-krill-ca

I moved this issue to the todo list for the upcoming release 0.5. We also aim to release a GUI in the short term that will help with this process.

**Comment by timbru** [comment]
We added a new error for this which will be included in the 0.5 release:

"Please configure the repository for CA 'ca' before adding parents"

Hopefully this makes it more clear what needs to be done in this case.
