### ISSUE TITLE
krill pid in .conf file?

### ISSUE THREAD

**Issue by geeohgeegeeoh** [NLnetLabs/krill#215]
for rc.d/ scripting on FreeBSD it would be a significant benefit if the pid file was either an argument to the daemon or set in the .conf file.

The current model of "get the process ID from the last command and write it by hand" is not a good fit for rc.d scripting.

I am using wrapper shellscripts for now, but would prefer this wasn't neccessary.

**Comment by timbru** [comment]
Good suggestion, I will move this to the to-do list for release 0.5.1 which is now planned for early April - given that I will be on holidays for the next two weeks.

**Comment by timbru** [comment]
Make that 0.6.0 - I planned to do a 0.5.1 before now, but I think the next release will be 0.6.0 because it will include some major internal changes as well as minor updates to the API.

**Comment by timbru** [comment]
This is now in master. You can try it, but master may be a bit unstable still because not all changes have been thoroughly tested yet.

Greetings from sunny Brazil.. trying to sort out a flight back home!

**Comment by geeohgeegeeoh** [comment]
thanks Tim. I'll give it a go. it will make rc.d much simpler (jaap is
coding that in the port/ for FreeBSD?)

-G
