### ISSUE TITLE
rc.d/krill for FreeBSD

### ISSUE THREAD

**Issue by geeohgeegeeoh** [NLnetLabs/krill#217]
This expects the following environment variables in `/etc/rc.conf`

```
#
krill_enable="YES"
krill_user="krill"
krill_pid="/var/run/krill.pid"
```
optionally, for installs not in /home/krill krill_cmd can be set to the path e.g. `/usr/local/bin/runKrill`

Then the following can be run via FreeBSD rc.d processes at boot time or `service krill [stop|start]`

/usr/local/etc/rc.d/krill

```
#!/bin/sh
# PROVIDE: krill
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name=krill
rcvar=krill_enable
start_cmd="${name}_start"
stop_cmd="${name}_stop"

load_rc_config $name
: ${krill_enable:=no}
: ${krill_user:="krill"}
: ${krill_cmd:="/home/krill/bin/runKrill"}
: ${krill_flags:="-c /home/krill/data/krill.conf"}
: ${krill_pid:="/var/run/krill.pid"}

krill_start()
{
        PID=$(su - ${krill_user} -c "${krill_cmd} ${krill_flags}")
        echo ${PID} > ${krill_pid}
}

krill_stop()
{
        su - ${krill_user} -c "/bin/kill $(cat ${krill_pid})"
}

run_rc_command "$1"
```

**Comment by Jakker** [comment]
Thank you for this suggestion. I'm nearly done with a FreeBSD port for krill and an rc.d scriot is one of the missing pieces. I'll take this as a base.

**Comment by Jakker** [comment]
Since the [release](https://www.freshports.org/net/krill/) of a port for krill there is a start up script based on you suggestion.
I'm happy to receive suggestions for improvements, preferably as a PR via the [FreeBSD bugzilla](https://bugs.freebsd.org/bugzilla/) website.
