### ISSUE TITLE
Action buttons on parent/repository

### ISSUE THREAD

**Issue by geeohgeegeeoh** [NLnetLabs/krill#219]
Can we get web controls to force-fetch out of time sequence/cron the parent state, and force re-publish please.

**Comment by AlexanderBand** [comment]
cc @enricoberti

**Comment by timbru** [comment]
After some discussion we want to move this to a future release where we will revise the 'parent' and 'repository' pages to include more useful information about the state of the conversation between your krill CA and its parents / repository.

**Comment by timbru** [comment]
Will be part of the upcoming 0.8 release. The parent and repository tabs now show more useful details and include a link to trigger syncing with the parents / repo.
