### ISSUE TITLE
running krill without https

### ISSUE THREAD

**Issue by ties** [NLnetLabs/krill#222]
I am setting up a lab environment in which Krill runs in a docker container behind a Traefik reverse proxy. Traefik would handle the SSL termination. 

In a set-up like this the container does not have (a fqdn with) a valid SSL certificate.

Would you consider making it possible to run krill without SSL? This is easier in reverse proxy scenario's when working with containers.

**Comment by timbru** [comment]
I believe this would add some complexity, and a window for mismanagement. Can't you tell your proxy to accept the self-signed certificate that Krill generates (if you use the default `https_mode = "generate"`)?

**Comment by timbru** [comment]
Mismanagement is my biggest concern here: I really want to avoid enabling plain text API access for CA management.

**Comment by ties** [comment]
I understand your concern and I agree with the default. This inconvenience for some users may be worth it over a foot-cannon (which ends up in tutorials etc).

It is possible configure traefik to accept self-signed certificates. For reference (since there are no directly usable examples of that, seels like the consider it to be an anti-pattern too):
```toml
# traefik.toml
# Allow ssl mismatches when connecting to backends
[serversTransport]
  insecureSkipVerify = true

# docker label on container:
#      - "traefik.http.services.service0.loadbalancer.server.scheme=https"
```
