### ISSUE TITLE
Documentation not clear on how to setup and publish to remote repository.

### ISSUE THREAD

**Issue by finlaydotb** [NLnetLabs/krill#247]
I am trying to run krill where the ca publish to a remote repository instead of using the embedded one. And I am having little luck. 

I run two instances of krill container. One will serve as the ca, the other will serve as the repository.

In the ca container, I create a ca handle, via the UI interface, then I generate the repo request by running `krillc repo request --ca ca1 > publisher_request.xml`

Now I go to the container that will serve as the repository, and this is where the documentation is really not clear on how to proceed.

In [Add a Publisher](https://rpki.readthedocs.io/en/latest/krill/remote-publishing.html#add-a-publisher) it says:

```
In order to add a publisher you have to get its RFC 8183 Publisher Request XML, and hand it over to the server:

$ krillc publishers add --publisher ca --rfc8183 ./data/ca-pub-req.xml
```
well when I run the `krillc publishers add --publisher ca --rfc8183 ./data/ca-pub-req.xml` command I get `Error: No embedded repository configured`

Am I supposed to configure an embedded repository? But that is not what I want though, I need a repository that can allow publishing from another ca.

Any pointers?

**Comment by timbru** [comment]
Hi, indeed this error message is somewhat confusing, and we will (we do need to) improve this part of the documentation!

You are getting this error because the Krill instance in your repository container is not configured to be a repository server. To do so make sure you need to uncomment and set the following variables in its configuration file:


```
# Specify whether an embedded repository should be started. For many users
# it will be better to use a repository server provided by a third party, e.g.
# the RIR or NIR under which resources are received.
#
# Note that an existing embedded repository server will be removed if this
# setting is set to 'false' (default) AND there are no current publishers (i.e.
# all CAs use an external repository).
#
### repo_enabled = false

# Specify the base rsync repository for this server. Publishers will get
# a base URI that is based on the 'publisher_handle' in the XML file.
#
# Note, you should set up an rsync daemon to expose $data_dir/rsync to serve
# this data. The uri defined here should match the module name in your rsync
# configuration.
#
# Furthemore.. note that the default 'localhost' is only allowed to be used
# when the KRILL_TEST ENV variable has been set.
#
### rsync_base = "rsync://localhost/repo/"

# Use the following if you want to use another public URI to access the RRDP files,
# e.g. because you serve them as raw files from another machine with a web server.
#
### rrdp_service_uri = "$service_uri/rrdp/"
```

I hope this solves your issue. I am closing this issue for now, but please let us know if it didn't.

**Comment by ximon18** [comment]
FYI this is how I was able to set up two Krill instances, one publishing to the other, using Krill Manager on Digital Ocean:

1. Create two Krill Manager DigitalOcean Droplets using the "Create Krill Droplet" button on the [DigitalOcean Marketplace page for Krill](https://marketplace.digitalocean.com/apps/krill?refcode=cab39584666c) (the smallest $5/month 1 GB/1 CPU is fine).

2. Use the [DigitalOcean Networking Domains portal page](https://cloud.digitalocean.com/networking/domains) to setup an A (and AAAA if you chose to enable IPv6 when creating your Droplet) record for each Droplet. In my case I set up one record (`ca.247-a.krill.cloud`) for the non-repo Droplet and three records for the repo Droplet (`ca.247-b.krill.cloud`, `rrdp.247-b.krill.cloud` and `rsync.247-b.krill.cloud`).

3. SSH into the first Droplet and initialize it to use a 3rd party repository:
```
ssh root@ca.247-a.krill.cloud
# krillmanager init
> Type: INITIALIZE, or FILE to supply an archive file path?: INITIALIZE
> Would you like to publish with a 3rd party? [YES/NO]: YES
> Certificate Authority name: ca1
> Krill domain: ca.247-a.krill.cloud
> Authentication token: *****
> Would you like to upload logs to an AWS S3 compatible service? [YES/NO]: NO
> NEW or OWN: NEW
(Let's Encrypt certificate is created for the ca subdomain)
> NEW, OWN, or USE: USE
...
```

**Note: ** Krill Manager automatically creates `ca1` for me in Krill.

4. SSH into the second Droplet and initialize it to be a repository:
```
ssh root@ca.247-b.krill.cloud
# krillmanager init
> Type: INITIALIZE, or FILE to supply an archive file path?: INITIALIZE
> Would you like to publish with a 3rd party? [YES/NO]: NO
> Certificate Authority name: ca2
> Krill domain: ca.247-b.krill.cloud
> RRDP domain: rrdp.247-b.krill.cloud
> Rsync domain: rsync.247-b.krill.cloud
> Authentication token: *****
> Would you like to upload logs to an AWS S3 compatible service? [YES/NO]: NO
> NEW or OWN: NEW
(Let's Encrypt certificate is created for the ca subdomain)
> NEW, OWN, or USE: USE
> NEW or OWN: NEW
(Let's Encrypt certificate is created for the rrdp subdomain)
> NEW, OWN, or USE: USE
...
```

**Note:** Krill Manager automatically creates `ca2` for me AND sets `repo_enabled = true` in the Krill configuration file.

5. SSH into the first Droplet and obtain the repo request XML from the "client" CA:
```
# krillc repo request --ca ca1 > /tmp/req.xml
```

**Note:** Krill Manager automatically sets the `--server` and `--token` environment variables for me so that I don't have to specify them when invoking `krillc`.

6. Copy the `/tmp/req.xml` file from the first Droplet to the second droplet.
7. SSH into the second Droplet and tell the repo to add the "client" as a publisher:
```
# krillc publishers add --publisher ca1 --rfc8183 /tmp/req.xml > /tmp/resp..xml
```

8. Copy the `/tmp/resp.xml` file from the second Droplet to the first droplet.
9.  SSH into the first Droplet and tell it to use the remote repository:
```
# krillc repo update remote --ca ca1 --rfc8183 /tmp/resp.xml
```

Now in the Lagosta UI of the first Droplet I see the remote repo:

![image](https://user-images.githubusercontent.com/3304436/83495870-8f19ec80-a4b8-11ea-952f-a408b2b17d23.png)

**END**

**Comment by finlaydotb** [comment]
Thanks for the tips. I was able to get past where I was stuck initially. I was able to generate the publisher request and add it to the other krill instance, and I got a response...

But now when I go back to the ca instance and submit the repsonse, I get the following error. I am attempting to use the UI to add the reponse

```
HTTP client error: Status: 400 Bad Request, Error: {"label":"pub-no-embedded-repo","msg":"No embedded repository configured","args":{}}
```
Have any idea what stupid thing I could be doing?

**Comment by timbru** [comment]
This looks like your CA is trying to contact itself when it get the response xml.

Does your service uri point to localhost? If so, it may be easiest to set up your repository instance from scratch again. Make sure that it is using a public (well accessible in your network anyway) host for the service uri, and world reachable uris for rsync and rrdp.

**Comment by finlaydotb** [comment]
Ok. So I was able to get it to work...

Now for the ca instance, I would like to generate certifcates and roas etc, so I figure, I will need a TA. enabling that via `KRILL_USE_TA=true` gives the error on startup:

`error: Cannot use embedded TA without embedded repository`

How will I be able to test run the ca instance, have a TA and use a remote repository?

**Comment by finlaydotb** [comment]
Also maybe a feature request...via the UI, the instance that should serve as the repository is still requiring a ca handle to be set. It would be nice if the UI adapts depending on if krill is running as a ca or as a repository.

**Comment by ximon18** [comment]
This might help: https://lists.nlnetlabs.nl/pipermail/rpki/2020-June/000169.html

**Comment by finlaydotb** [comment]
> This might help: https://lists.nlnetlabs.nl/pipermail/rpki/2020-June/000169.html

Unfortunately not. For one, I would not be able to use the krill manager option


> It also means that there are some limitations at present, e.g. the TAL only 
> supports HTTPS, not Rsync, the resources assigned to the TA are 
> hard-coded and cannot be changed, and when you set "use_ta = true" Krill 
> currently assumes that you have also set "repo_enabled = true"

If I understand this correctly, this means you cannot use a remote repository, if you need to use an embedded TA?

**Comment by ximon18** [comment]
You do need to use Krill Manager, it simy helps by doing things for you that you can instead do yourself, it’s just more effort.

The Krill instance that is acting as a test trust anchor must also have ‘repo_enabled = true’. That does not prevent a child CA from publishing to a remote repo.

**Comment by ximon18** [comment]
For the child CA you need to do two RFC 8183 up/down registration steps, one to register it as a publisher with the repo and the other to register it as a child of the parent CA or TA.

The repo up/down is done via the commands krillc repo request (on the client krill), krillc publishers add (on the repo krill) and krillc repo update (on the client krill again).

The child/parent up down is done via the commands krillc parents request (on the child krill), krillc children add (on the parent krill) and krillc parents add (on the child krill).

To add roas use the krillc roas update command on the child krill. For those roas to be served you must set up something to serve them via rrdp / rsync from the krill data/repo/ sub dirs, e.g. nginx and rsyncd.

For relying party software that supports a HTTPS TAL such as Routinator to traverse the test RPKI hierarchy and find the ROAs you must give it the test TAL file, available at /ta/ta.tal on the ta krill instance.

**Comment by timbru** [comment]
The ta can only be enabled on the instance that is running the repository.

Thank you for trying this out and talking to us!

Updating the documentation on this has been overdue.. we were focusing so much on running krill under a parent ca and provided repository that this did not get the attention it deserves.

Will make it a priority!

**Comment by timbru** [comment]
Also note.. you will have to use the cli to add your child to the ta.

The ui does not yet support adding children.

As said we will revise the documentation on this. For now please use:

`krillc help children add remote`

To see how this is done

**Comment by finlaydotb** [comment]
Thanks all for the responses...I have not yet got to my work computer so I am yet to try out the various suggestions...

but I can't help but notice something that sounds contradictory in the responses...

@ximon18 you said:
 
> The Krill instance that is acting as a test trust anchor must also have repo_enabled = true. That does not prevent a child CA from publishing to a remote repo.

while @timbru you said:

> The ta can only be enabled on the instance that is running the repository.

If the ta can only be enabled on the instance that is running the repository, then it is not possible for the krill instance that is acting as a test trust anchor (which is not running the repository), to have a child CA

or I am misinterpreting what has been said?

**Comment by finlaydotb** [comment]
> If the ta can only be enabled on the instance that is running the repository, then it is not possible for the krill instance that is acting as a test trust anchor (which is not running the repository), to have a child CA

Except the instance running as a ta, has an embedded repository enabled, which makes it possible to have a child CA, but the child CA then publishes to another remote repository...

This interpretation seems to make sense to me...and I guess that is what is being communicated? Anyways, I will try things out in a bit and report to you guys :) Thanks!

**Comment by timbru** [comment]
Indeed, the other CAs can publish remotely.
