### ISSUE TITLE
Delegation of resource fails depending on order of parent/child relationship setup

### ISSUE THREAD

**Issue by dadepo** [NLnetLabs/krill#262]
I realise if I add `ta` as parent of `ca_in`, then add `ca_in` as a child of `ta` the resources delegated as part of setting up this relationship does not show up in `ca_in`.

But if I first add `ca_in` as a child of `ta` then setup `ta` as a parent of `ca_in` then the resources delegated to `ca_in` shows up in `ca_in`

See relevant snippet of cli output:

### Add parent -> Add child and resource
```
/ # krillc parents add embedded --ca ca_in --parent ta --token itworks

/ # krillc children add embedded --ca ta --token itworks --child ca_in
You must specify resources when adding a CA (--asn, --ipv4, --ipv6)

/ # krillc children add embedded --ca ta --token itworks --child ca_in --ipv4 "100.0.0.0/8,200.0.0.0/8"
Embedded parent
/ # krillc show --ca ca_in
Name:     ca_in

-- snip --

# no resources
**Total resources: <none>**

Parents:
Handle: ta Kind: Embedded parent

Children:
<none>
```
### Add child and resource -> Add parent

```
/ #  krillc children add embedded --ca ta --token itworks --child ca_in
You must specify resources when adding a CA (--asn, --ipv4, --ipv6)

/ # krillc children add embedded --ca ta --token itworks --child ca_in --ipv4 "100.0.0.0/8,200.0.0.0/8"
Embedded parent

/ # krillc parents add embedded --ca ca_in --parent ta --token itworks

/ # krillc show --ca ca_in
Name:     ca_in

-- snip --

# resources shows up
Total resources:
    ASNs:
    IPv4: 100.0.0.0/8, 200.0.0.0/8
    IPv6:

Parents:
Handle: ta Kind: Embedded parent

Resource Class: 1
Parent: ta
State: active    Resources:
    ASNs:
    IPv4: 100.0.0.0/8, 200.0.0.0/8
    IPv6:
Current objects:
  8B3014AF6D41F85E4775147BD82B5F9638F2D097.mft
  8B3014AF6D41F85E4775147BD82B5F9638F2D097.crl

Children:
<none>
```
The intended flow might very well be `Add child and resource -> Add parent` then perhaps the other order should be disallowed or adequate _warning_ message is shown. The current feedback message `You must specify resources when adding a CA (--asn, --ipv4, --ipv6)` even suggests that one is one right path...

**Comment by timbru** [comment]
If you add the embedded parent `ta` to `ca_in` before `ta` has learned about `ca_in`, then `ca_in` will request resources and get a reply that amounts to: I do not know you. Then when you add `ca_in` as a child to `ta` no certificate can be issued: there is no request from `ca_in`. This will happen an hour later when `ca_in` will check its parents again, or you can trigger this with the `bulk` operation.

All this said, I believe this is a non-issue, or at least will be in 0.7 that we will release next week. The `embedded` option offers marginal performance benefits when testing multiple CAs in a single Krill, but the price is complexity of use.

For this reason the 0.7 CLI will no longer have the options `embedded` vs `remote`. The `remote` way of doing thing by exchanging XML files will always be used. This also means that it will be impossible to add a parent - which requires a response XML - before that parent has processed the child request XML.
