### ISSUE TITLE
Tweak republish intervals

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill#281]
Currently Krill:
- Checks for republication every 1 hour
- Republishes CRL/MFT if their next update < 8 hours in future
- Re-issues CRL/MFT with next update time 24 hours in future, end EE expiry 7 days in future

This means that republication happens every 16-17 hours, leaving 7-8 hours to deal with issues if things go stale. It creates a soft replay window of 24 hours, and a hard limit of 7 days.

Perhaps we need different numbers, like:
- check every 10 minutes (nothing happens if there is nothing to do)
- republish 24 hours in advance of next update time 
- use 36 hour next update time

Or we could even make this user configurable.. with sane defaults of course.

Please feel free to comment!

**Comment by ties** [comment]
First of all: as a CA operator (for a lab environment) I appreciate the additional time this gives me to react to issues. 

> * check every 10 minutes (nothing happens if there is nothing to do)

For a CA with many objects created at different points in time this could lead to a lot more manifest updates/churn. Checking less frequently is an implicit form of batching.

I'm not sure if there are recommended defaults published somewhere?
