### ISSUE TITLE
Docker build fails with error[E0658]: `cfg(doctest)` is experimental and subject to change in xml-rs

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#309]
A few days ago this worked but since this morning I'm now seeing the following error when bulding the Krill Docker image:

```bash
$ docker build -t deleteme .
Sending build context to Docker daemon    146MB
Step 1/23 : ARG BASE_IMG=alpine:3.11
Step 2/23 : FROM ${BASE_IMG} AS build
 ---> f70734b6a266
Step 3/23 : RUN apk add rust cargo openssl-dev
 ---> Using cache
 ---> 72912a494474
Step 4/23 : WORKDIR /tmp/krill
 ---> Using cache
 ---> 6c4e2d26ca47
Step 5/23 : COPY . .
 ---> 70cd386a1ccc
Step 6/23 : RUN cargo build --target x86_64-alpine-linux-musl --release
 ---> Running in cbb00420b6c5
    Updating crates.io index
    Updating git repository `https://github.com/NLnetLabs/rpki-rs.git`
 Downloading crates ...

...

   Compiling xml-rs v0.8.3
error[E0658]: `cfg(doctest)` is experimental and subject to change
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/xml-rs-0.8.3/src/lib.rs:9:7
  |
9 | #[cfg(doctest)]
  |       ^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/62210
```

Observation: The Dockerfile uses `apk add rust`. Bumping the base alpine version from `3.11` to `3.12` causes `apk add rust` to pull in newer rust stable which causes this poblem to go away.

@timbru: A coulpe of questions:

1. Should we align the rust version used in our various build processes? E.g. GitHub Actions builds, `.deb` package builds, Docker image builds?

2. Do you see any issue with bumping the Alpine base verson used by the image? (note: Routinator already uses the newer 3.12 version).

Ximon

**Comment by timbru** [comment]
newer version sounds good!

**Comment by ximon18** [comment]
Update: this only affects the 0.8.0-RC-dev branch, not master.
