### ISSUE TITLE
error: reached the type-length limit while instantiating `tokio::runtime::Handle::enter::<...

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#310]
Seen with Rust 1.46.0-beta.5 compiler used by the GitHub Actions rust-beta build of Krill when building the `0.8.0-RC-dev` Krill branch.

E.g. from https://github.com/NLnetLabs/krill/pull/308/checks?check_run_id=1025592938#step:4:663

```
error: reached the type-length limit while instantiating `tokio::runtime::Handle::enter::<...:{{closure}}#4]>}]>, ()}]>], ()>`
##[error]  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/handle.rs:30:5
   |
30 | /     pub fn enter<F, R>(&self, f: F) -> R
31 | |     where
32 | |         F: FnOnce() -> R,
33 | |     {
34 | |         context::enter(self.clone(), f)
35 | |     }
   | |_____^
   |
   = note: consider adding a `#![type_length_limit="1610014"]` attribute to your crate

error: aborting due to previous error

error: could not compile `krill`.
```

**Comment by timbru** [comment]
This seems to be related to extensive use of futures, and possibly generics and macros as well, which cause the compiler to do a large number of substitutions as part of it 'Monomorphization' -- which is how it supposedly achieves zero-cost (runtime cost) abstractions.

See more here:
https://doc.rust-lang.org/reference/attributes/limits.html

It may be possible to stay below the threshold by using boxed futures:
https://users.rust-lang.org/t/exponential-type-size-of-async-function/36852

However, this would require quite extensive work, and it does not seem to cause any runtime issues to raise the compiler limit. So doing that, at least for now.
