### ISSUE TITLE
Error when executing "krillc publishers list"

### ISSUE THREAD

**Issue by racompton** [NLnetLabs/krill#315]
```
ubuntu@krill-eval:~$ krillc publishers list
Error: Persistence error: EOF while parsing a value at line 1 column 0
```

FYI, I don't believe I have defined any publishers yet.

**Comment by racompton** [comment]
FYI, looks like "krillc publishers stats" also returns the same error.

**Comment by timbru** [comment]
I know (through other channels) that you had a full disk.

I think what may have happened is that Krill was unable to save its state properly and there are now incompletely written json files in your `data/pubd/0` directory. Krill tries to read them to rebuild its state in memory and then things fail.

I will move this is issue to the 0.8 release plan. I think that on start-up Krill should check all state.

Input on how is welcome, but I am leaning towards letting Krill check and exit with an error in case of issues, and providing a '--recover' flag or something to let Krill figure out what consistent history is available and rebuild its state to that point - and remove any changes from after this point.

If you want to check things manually then see which files are empty and just delete them. If you delete the snapshot it should rebuild based on deltas. Verify though that the info.json matches what you expect after deleting files. And that you have all deltas leading to that version number. Example file:
```
{
  "snapshot_version": 5,
  "last_event": 7,
  "last_command": 7,
  "last_update": "2020-08-27T11:29:30.712682Z"
}
```

**Comment by timbru** [comment]
You may have similar issues for your CA. So under `data/cas/..` you will find a similar structure.

**Comment by timbru** [comment]
This is proving to be valuable, but hard work. List of things to keep track of:

- [X] Warm up the cache on start up, flag issues
- [X] Recover to last possible 'reconstructible' state
- [ ] Produce back-up snapshots (avoid issue with partially written snapshot)
- [ ] Clean up surplus events
- [ ] Refactor keystore (need more highlevel functions, lowlevel storage can smaller)

**Comment by timbru** [comment]
Seems to work now. Will need more proper testing in the wild in RC!
