### ISSUE TITLE
BSD support

### ISSUE THREAD

**Issue by cardosocristian** [NLnetLabs/krill#354]
Is there any possibility of having Krill + Routinator on BSD systems?

**Comment by timbru** [comment]
Which kind of *BSD systems are you referring to?

You could install rust and cargo and compile Krill (and Routinator) yourself:
https://rpki.readthedocs.io/en/latest/krill/install-and-run.html#installing-with-cargo

However, support for Rust on OpenBSD can be problematic from what I read. There are some versions available but they can lag behind a bit and Krill or its dependencies (more likely) may need more recent versions. Unfortunately, I have little experience with OpenBSD myself.

**Comment by cardosocristian** [comment]
I mean FreeBSD

**Comment by timbru** [comment]
Hi,

On FreeBSD you can install rust and cargo and compile Krill as mentioned above.

But, our colleague @Jakker has also made a port for routinator, and krill will be added in future:
https://www.freebsd.org/cgi/ports.cgi?query=routinator&stype=all

I hope this helps. I will close the issue for now, but feel free to re-open if you have any more issues.

If you are deploying Krill, or even just testing with it, you may also want to subscribe to our mailing list:
https://lists.nlnetlabs.nl/mailman/listinfo/rpki

For testing Krill safely outside of any real RPKI Trust Anchor you can use our testbed service which is described here:
https://blog.nlnetlabs.nl/testing----123-delegated-rpki/

In that blogpost Krill Manager is used to set up Krill locally, but of course, it will also work with other Krill installations.
