### ISSUE TITLE
Packaging for krillpubd/c

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill#361]

**Comment by ximon18** [comment]
We need to decide if we want a single DEB containing all four binaries (`krill`, `krillc`, `krillpubd` and `krillpubc`) or separate DEBs for CA/CombinedLegacy and for PUB.

The question for a single DEB is what to do with the systemd services? For an upgrade of an existing Krill installation IIRC it will continue to work with the original `krill` binary which will run in combined mode. For new installations there won't be an existing data dir and Krill will refuse to run as a publisher and will want the separate `krillpubd` to be run instead - which should be its own systemd service.

What about for situations where the CA should run on one machine and the PUB on another? You wouldn't want both CA and PUB services active on both machines. Perhaps it's fine to include both services both initially disabled (as is already the case for the current DEB) and then users only configure and activate the CA or the PUB, or stick with the combined approach if they were already using Krill?

**Comment by timbru** [comment]
No need. Reverting separation of krillpubd/c. See issue #527
