### ISSUE TITLE
Upgrade dependencies for 0.9 (tokio, reqwest, rpki-rs, bcder..)

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill#366]
- [x] run `cargo audit`
- [x] minimum rust 1.44 see NLnetLabs/routinator#444
- [x] build with min. rust version

**Comment by ximon18** [comment]
See also #447.

**Comment by ximon18** [comment]
@timbru: Regarding `minimum rust 1.44` the Krill minimum is already 1.45.
