### ISSUE TITLE
Ensure login credentials & session state are properly protected

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#382]
Note: This relates to the `multi-user` feature in the `v0.8.1-bis` branch.

**Comment by ximon18** [comment]
According to https://www.imperialviolet.org/2015/05/16/aeads.html the nonce ensures that the same input encrypts to different output, e.g. the example given is encrypting individual key presses and being able to see repeats in the encrypted data caused by the same key encrypting to the same value.

In the case of the OpenID Connect provider the input being encrypted is different on every session assuming that the expiration time and access token value both change on each login. For the config file user provider there is no such varying input so the nonce (or introducing some variation in the input) is more important.

The nonce is needed on encrypt and decrypt thus it cannot be a random value (unless we can retrieve that random value reliably  and safely when decrypting).

In other related news, we use AES GCM 256 AEAD encryption but session storage. According to [this](https://soatok.blog/2020/07/12/comparison-of-symmetric-encryption-methods/#aes-gcm-vs-chacha20poly1305) and [this](https://latacora.micro.blog/2018/04/03/cryptographic-right-answers.html) we should prefer ChaCha20-Poly1305 (also available via the Rust `openssl` crate) over AES GCM 256.

And we use SHA-256 hashing for passwords but according to [this](https://latacora.micro.blog/2018/04/03/cryptographic-right-answers.html) we absolutely should not and should instead use _"In order of preference, use scrypt, argon2, bcrypt, and then if nothing else is available PBKDF2"_.

**Comment by ximon18** [comment]
The Rust OpenSSL crate appears to have support for scrypt, and on the Lagosta side there is an [scrypt-js](https://www.npmjs.com/package/scrypt-js) NPM package that could be used.

**Comment by ximon18** [comment]
Note this quote fomr https://www.imperialviolet.org/2015/05/16/aeads.html about nonce uniqueness and AES GCM and ChaCha20-Poly1305:

> It would be nice if reusing an nonce just meant that the same plaintext would result in the same ciphertext. That's the least bad thing that an AEAD could do in that situation. However the reality is significantly worse: common AEADs tend to lose confidentiality of messages with a repeated nonce and authenticity tends to collaspe completely for all messages. (I.e. it's very bad.) We like these common AEADs because they're fast, but you must have a solid story about nonce uniqueness. AEADs like AES-GCM and ChaCha20-Poly1305 fail in this fashion.

**Comment by ties** [comment]
not a cryptographer: but use a cryptographic random number source for a
nonce.

And ask a cryptographer if possible, these low level primitives are foot
cannons.

**Comment by ximon18** [comment]
Yup, thanks @ties, already understood but nice to know that someone is paying attention.

The source of randomness for the nonce is not the problem being considered here (though is a concern in general with cryptography of course), the difficulty lies in having the same nonce securely and reliably available both at the moment of encryption and decryption of a given session token while not storing state where avoidable/not limiting future clustering support and also while not using the same nonce for multiple sessions.

Keep in mind that encryption here is not for an ongoing stream of communication between two parties but rather for persistent secure storage and retrieval both by the same party (although in the distributed deployment scenario this looks more like traditional send and receive between two parties).

Either the nonce needs to be "shared", or the server must be able to determine it from known facts/sources.

**Comment by timbru** [comment]
Is there something we could do similar to `KrillSigner::random_serial`? Perhaps not *that* function, but essentially letting the `KrillSigner` source the random, so we can have openssl now and HSMs in future?

**Comment by ximon18** [comment]
Indeed I think it makes sense to group the functionality that uses the `openssl` crate together behind a facade that enables us to swap it out later, there's already a comment to that effect at the top of `crypt.rs`. In this particular case however please note that I'm not explcitly sourcing any random, I'm just using the `openssl` crate AEAD en/de-cryption functions and telling them which "cipher" to use. I didn't move that into the "signer" as it's not about signing, but as said there may be grounds for refactoring later.

**Comment by ximon18** [comment]
@ties: Regarding low level primitives and foot-guns, I completely agree. In this case I'm not composing low level crypto primitives myself precisely for this reason but am instead using AEAD based en/de-cryption which uses groupings of low level crypto primitives chosen by crypto experts, I only have to supply suitable nonce value and "additional data" (AAD) values.

**Comment by ximon18** [comment]
I briefly tried but was unable to get `scrypt` support via the Rust `openssl` crate to work, it either complained about out of memory or the obscure "OpenSSL error" message. It does work just fine however with the `scrypt` crate but that's unfortunately another dependency. Using bcrypt or argon2 are also not supported by the Rust `openssl` crate. OpenSSL does have password hashing algorithms, but not scrypt, bcrypt or argon2 as far as I can see. Relying on OpenSSL could also be problematic if using the host O/S OpenSSL rather than "vendored/static" OpenSSL as it may not support the hash function we want to use.

Once using a salted password hashing approach there is also the quesiton of where to store the salt and whether to use one global salt or one per user or even one per password (e.g. if resetting a password). Looking at the [OWASP Application Security Verification Standard](https://owasp.org/www-project-application-security-verification-standard/) and other sources (e.g. [this](https://crackstation.net/hashing-security.htm)) it is clear that the guidance is to use a salt per password and to NOT share that salt with the client browser. Instead the only advice I have been able to find is to use two salts, on in the client browser based on the logging in user identity (e.g. email, username) and some site specific identifier, and a separate per password salt on the server. This prevents sending the password to the server while overcoming the problem of sharing the salt with the client browser. The purpose of these extra efforts is to prevent attack via stock rainbow tables and to prevent leaked lists of password hashes being directly usable as login tokens.

I can add support for separate client and server hashing based on scrypt. Regarding the encryption of the session I can make the nonce and AAD unique per installation. Making them unique per login is more challenging.

However, as we already note in the end user facing Krill multi-user documentation, handling passwords directly is risky and complicated and it is much better to delegate handling of credentials to a 3rd party provider such as an OpenID Connect compliant provider.

At present it might be best to just note the known limitations. The protections in multi-user mode Krill already far exceed what is possible without multi-user mode. I started, but didn't finish, going through the OWASP Application Security Verification Standard 4.0.2 compliance checklist. Completing that (from the perspective of user login and login sessions iwhtin Krill) and sharing it would give more insight into where we currently stand compared to best practices.

@timbru, @AlexanderBand: let's discuss how to proceed.

**Comment by ties** [comment]
> Once using a salted password hashing approach there is also the quesiton of where to store the salt and whether to use one global salt or one per user or even one per password (e.g. if resetting a password). Looking at the [OWASP Application Security Verification Standard](https://owasp.org/www-project-application-security-verification-standard/) and other sources (e.g. [this](https://crackstation.net/hashing-security.htm)) it is clear that the guidance is to use a salt per password and to NOT share that salt with the client browser. Instead the only advice I have been able to find is to use two salts, one in the client browser based on the logging in user identity (e.g. email, username) and some site specific identifier, and a separate per password salt on the server. This prevents sending the password to the server while overcoming the problem of sharing the salt with the client browser. The purpose of these extra efforts is to prevent attack via stock rainbow tables and to prevent leaked lists of password hashes being directly usable as login tokens.

That may not even be a choice: if I recall correctly, scrypt, argon2, and bcrypt always generate a separate salt per password. You COULD add a application-specific secret to the plaintext (`h(plaintext|secret)`) to prevent brute-forcing - but I think the recommendation is to set the work factor high enough to make a brute-force attack untenable.

The discussion may be clearer if you separate symmetric-encrypted storage of state from the storage of passwords? For the first I would stick to [high level apis](https://github.com/veorq/cryptocoding#provide-high-level-apis) over low-level primitives. The latter is a much more clear-cut case.

**Comment by ximon18** [comment]
Hi @ties.

Indeed this is about high-level APIs, and indeed this issue started off being just about one aspect but I have broadened it out a bit. I wasn't suggesting that we use a single salt, I was just summarizing my findings.

At present I have locally working changes based on scrypt with per user per password salt and separate client and server salting. I have tried a few work factor values but where possible will use the defaults, e.g. the default of the NodeJS crypto scrypt function, I would only lower it if it is far too slow for the end user login experience.

However, even if I improve everything I have mentioned this will not be the same as having performed a complete audit of the code against best practices and/or using outside experts etc. Hence my suggestion to make clear what is or isn't supported or is a risk and to guide users to use OpenID Connect because 3rd party providers should in theory have much more resource and expertise to ensure their authentication platform is secure. We should also keep in mind what kind of data are we protecting, what is the context, what is acceptable or not in that context, etc.

Ximon

**Comment by ties** [comment]
Let's make that: definitely use a salt per password otherwise rainbow tables still work. And definitely don't use a simple hash instead of a key derivation function or you'll end up in this situation: https://twitter.com/danielverlaan/status/1382731713495904256?s=19

(just pasting this because it is very timely wrt this discussion)

**Comment by ximon18** [comment]
@ties: I pushed a PR yesterday (linked to this issue) that uses ChaCha2-Poly1305 instead of AES-GCM for encryption of session state, and uses scrypt (with hashing on both client and server) instead of SHA-256.

**Comment by ximon18** [comment]
Summary of the nonce and AAD situation:

1. The nonce and AAD are inputs to the ChaCha20-Poly1305 encryption of login session state which is done by the config-file and openid-connect Krill authentication types.
2. The encrypted session state is passed to the client and is passed back as the HTTP Authorization header bearer token value.
3. It contains details like the users attributes, e.g. role, team membership, and in the case of openid-connect it also contains the access token and refresh token issued by the provider, as it is needed to obtain a new token and/or to revoke the token at the provider. It also contains the session start time.

The Additional Authenticated Data is just that, additional. It is sent in plain text thus is not encrypted but can be authenticated. It is intended for things like network packet port and IP address which must be in the clear but should be bound to the encrypted payload. In this case we don't have any such data that we wish to send along with the encrypted data. So we can use an empty AD value.

Regarding the nonce, the common understanding seems to be that:

> It is essential for security that the nonces be constructed in a
> manner that respects the requirement that each nonce value be
> distinct for each invocation of the authenticated encryption
> operation, for any fixed value of the key.
>
> Source: https://tools.ietf.org/html/rfc5116#section-3.1

In our case the key is fixed for the lifetime of the Krill instance or until the Krill operator deletes the key file and restarts Krill thereby causing a new key to be generated. So the nonce has toe be different for every encryption operation. However, it seems that the nonce does not need to be secret and so can be sent along with the cipher text. For example:

> Note that there is no need to coordinate
> the details of the nonce format between the encrypter and the
> decrypter, as long the entire nonce is sent or stored with the
> ciphertext and is thus available to the decrypter.
>
> Source: https://tools.ietf.org/html/rfc5116#section-3.1

And:

> A primary differentiator between a nonce and a key is that a nonce does not necessarily need to be considered secret; 
> exposing the value of the nonce should not reduce the overall security of the protocol. Both parties need the value to 
> encrypt/decrypt a message, but access to only the nonce or nonce+ciphertext/plaintext should not expose any
> information about the key.
>
> Source: https://samheslop.com/posts/20190203_understanding_nonce_reuse_plaintext_recovery.html

RFC 5116 has a [section on how to generate nonce values](https://tools.ietf.org/html/rfc5116#section-3.1). [RFC 8439](https://tools.ietf.org/html/rfc8439) regarding ChaCha20 says this about constructing nonce values:

> In cases where a single key is used by
> multiple senders, it is important to make sure that they don't use
> the same nonces.  This can be assured by partitioning the nonce space
> so that the first 32 bits are unique per sender, while the other 64
> bits come from a counter.

In a cluster Krill deployment where each Krill node uses the same encryption key, each node should thus use a unique initial 32-bit sendar part of the nonce.
