### ISSUE TITLE
Inconsistent and unacceptable token references

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#433]
We have various multiple inconsistent uses of the term `TOKEN` which could be confusing for the operator. We should make this more consistent. We also have token related references that include the unfortunate term 'master' which, while common in computing may cause offense. Any references to `master` should be removed.

For example, in the `defaults/krill.conf` config file it refers to `auth_token` and `KRILL_AUTH_TOKEN` yet the `krillc` help output says `-t, --token <string>    The secret token for the krill server. Or set env: KRILL_CLI_TOKEN`. As the token is not just for CLI usage but also can be used to login via the web UI, I would advocate using `AUTH_TOKEN` rather than `CLI_TOKEN`.

I propose the following changes regarding token naming consistency:

| File | Current | Proposed |
|---|---|---|
| `debian/postinst` | `GENERATED_TOKEN` | `KRILL_AUTH_TOKEN` |
| `defaults/krill-pubd.conf` | `KRILL_AUTH_TOKEN` | No change |
| `doc/openapi-pubd.yaml` | `KRILL_AUTH_TOKEN` | No change |
| `doc/openapi.yaml` | `KRILL_AUTH_TOKEN` | No change |
| `docker/entrypoint.sh` | `KRILL_AUTH_TOKEN` | No change |
| `src/cli/options.rs` | `KRILL_CLI_TOKEN` | `KRILL_AUTH_TOKEN` |
| `src/cli/options.rs` | `KRILL_CLI_TOKEN_ARG` | `KRILL_AUTH_TOKEN_ARG` |
| `src/cli/options.rs` | `KRILL_CLI_TOKEN_ENV` | `KRILL_AUTH_TOKEN_ENV` |
| `src/constants.rs` | `KRILL_ENV_AUTH_TOKEN` | `KRILL_AUTH_TOKEN_ENV` |
| `src/constants.rs` | `KRILL_CLI_TOKEN_ARG` | `KRILL_AUTH_TOKEN_ARG` |
| `src/constants.rs` | `KRILL_CLI_TOKEN_ENV` | `KRILL_AUTH_TOKEN_ENV` |
| `src/constants.rs` | `ACTOR_DEF_MASTER_TOKEN` | `ACTOR_DEF_AUTH_TOKEN` |
| `src/daemon/auth/policy.rs` | `master-token` | `auth-token` |
| `src/daemon/auth/policy.rs` | `ACTOR_DEF_MASTER_TOKEN` | `ACTOR_DEF_AUTH_TOKEN` |
| `src/daemon/providers/master_token.rs` | `ACTOR_DEF_MASTER_TOKEN` | `ACTOR_DEF_AUTH_TOKEN` |
| `src/daemon/config.rs` | `KRILL_ENV_AUTH_TOKEN` | `KRILL_AUTH_TOKEN_ENV` |
| `src/daemon/config.rs` | `master API key` | `auth token` |
| `src/daemon/config.rs` | `KRILL_AUTH_TOKEN` | No change |
| `test-resources/krill-init-multi-user.conf` | `KRILL_AUTH_TOKEN` | No change |
| `test-resources/krill-init.conf` | `KRILL_AUTH_TOKEN` | No change |

And the following changes to remove references to `master`, mostly relating to the auth token:

| File | Current | Proposed |
|---|---|---|
| `defaults/abac.polar` | `master-token` | `auth-token` |
| `defaults/krill-multi-user.conf` | `master-token` | `auth-token` |
| `defaults/krill-pubd.conf` | `master token` | `auth token` |
| `defaults/krill.conf` | `master token` | `auth token` |
| `defaults/rules.polar` | `master-token` | `auth-token` |
| `src/daemon/auth/authorizer.rs` | `master_token_provider` | `auth_token_provider` |
| `src/daemon/auth/authorizer.rs` | `master token` | `auth token` |
| `src/daemon/auth/policy.rs` | `master-token` | `auth-token` |
| `src/daemon/auth/policy.rs` | `ACTOR_DEF_MASTER_TOKEN` | `ACTOR_DEF_AUTH_TOKEN` |
| `src/daemon/auth/providers/mod.rs` | `master_token` | `auth_token` |
| `src/daemon/config.rs` | `MasterToken` | `AuthToken` |
| `src/daemon/krillserver.rs` | `master server` | `server` |
| `test-resources/krill-init-multi-user.conf` | `master token` | `auth token` |
| `test-resources/krill-init-multi-user.conf` | `master-token` | `auth-token` |
| `test-resources/krill-init.conf` | `master token` | `auth token` |
| `test-resources/ui/multi_user_master_token.conf` | `master-token` | `auth-token` |
| `test-resources/ui/testbed_ui.conf` | `master-token` | `auth-token` |
| `tests/auth_check.rs` | `master token` | `auth token` |
| `test-resources/ui/multi_user_master_token.rs` | `multi_user_master_token` | `multi_user_auth_token` |
| `tests/ui/cypress/specs/multi_user_config_file.js` | `master token` | `auth token` |
| `tests/ui/cypress/specs/multi_user_master_token.js` | `master` | `auth` |
| `tests/ui/cypress/specs/multi_user_master_token.js` | `master-token` | `auth-token` |
| `tests/ui/cypress/support/index.js` | `.../blob/master/...` | Replace the URL with `"Handling errors" at https://docs.cypress.io/examples/examples/recipes.html#Fundamentals` |
| `src/daemon/http/tls.rs` | `https://github.com/seanmonstar/warp/blob/master/src/tls.rs` | `https://github.com/seanmonstar/warp/` |

And rename the following files:

| Full path | Current Name | Proposed Name |
|---|---|---|
| `src/daemon/providers/master_token.rs` | `master_token.rs` | `auth_token.rs` |
| `test-resources/ui/multi_user_master_token.conf` | `multi_user_master_token.conf` | `multi_user_auth_token.conf` |
| `test-resources/ui/multi_user_master_token.rs` | `multi_user_master_token.rs` | `multi_user_auth_token.rs` |
| `tests/ui/cypress/specs/multi_user_master_token.js` | `multi_user_master_token.js` | `multi_user_auth_token.js` |

**Note::** There will still be some remaining references to master, which should be changed, but as a separate task. E.g. the git `master` branch and references to it in `.github/workflows/*.yml`. Changing these might require additional actions to ensure that existing developers or `cargo install --git` users are not impacted by the dissappearance of the branch they are currently using, e.g. updating `build.rs` as was done for the Routinator project.

**Note::** We may also need to update external documentation e.g. at https://rpki.readthedocs.io/.

**Comment by timbru** [comment]
As discussed, let us use "admin token" consistently.

**Comment by timbru** [comment]
The `master` branch can be renamed to `main` after the next release candidate has been merged.
