### ISSUE TITLE
Translate any new error or feedback English texts shown by the Lagosta UX

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#577]

**Comment by ximon18** [comment]
No new external facing error codes were introduced, all signer issues are reported via the internal `SignerError` type which is delivered to clients as error code `sys-signer` with an English error description generated within Krill that is not translated, only generic error text associated with `sys-signer` errors can be translated.

**Comment by timbru** [comment]
No need, this is not reported in the UI.
