### ISSUE TITLE
Feature request: permit disabling use of `prompt=login` with OIDC

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#614]
From issue #608.

When using OpenID Connect Krill automatically adds `prompt=login` to the OpenID Connect provider login URL. With KeyCloak however it has been reported that this _"causes Keycloak to always ask for my password, even if I have an existing SSO session. An option to turn this off would be nice"_.

In the Krill code there is a note next to the code that causes this behaviour:

```rust
// From https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest:
//   "prompt: login - The Authorization Server SHOULD prompt the
//    End-User for re-authentication. If it cannot re-authenticate the
//    End-User, it MUST return an error, typically login_required."
// We set this because the only time a user of Lagosta should be sent
// to the OpenID Connect: provider login form is when they actually want
// to specify who to login as, we don't want the provider somehow
// automatically completing the login process because it has some notion
// of an existing login session.
request = request.add_prompt(CoreAuthPrompt::Login);
```

Adding an option to disable this behaviour if desired seems reasonable. It may also be okay to remove this entirely, I'm not sure.

**Comment by ximon18** [comment]
Some thoughts on this:

1. Changing the default behavior would be a breaking change.

2. The default behavior errs on the side of security which in principle doesn't seem like a bad idea.

So for these reasons I'm inclined to just add an option as requested to disable the default behaviour.

- @TheEnbyperor: Have you tried removing prompt=login from the generated login redirect URL to confirm that this actually solves the problem that you reported?

**Comment by TheEnbyperor** [comment]
> Have you tried removing prompt=login from the generated login redirect URL to confirm that this actually solves the problem that you reported?

Yes, it works as intended. Agreed that it should be a default option to stay how it is.

**Comment by ximon18** [comment]
@TheEnbyperor: Does [this proposed conduct file syntax extension](https://github.com/NLnetLabs/krill/commit/0efc1a6f4d9a268f756267962a7b64304f3a724e) work for you?

**Comment by TheEnbyperor** [comment]
![shark-lgtm](https://user-images.githubusercontent.com/7520894/127405378-f083cd27-f7fb-4d87-8416-8b2e35f76932.png)
