### ISSUE TITLE
Suspend inactive child CAs

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill#623]
If child CAs turn out to be deactivated, then they will leave a valid certificate with their parent - but typically their manifest and CRL will have expired.

Unfortunately there is nothing in RFC 6492 that says how often child CAs MUST check back with their parent CA(s). Nor is there any normative language on how often they MUST publish and what a typical 'next update' time would be.

That said, Krill CAs will by default check with their parent every 10 minutes and publish MFT/CRLs with a next update time 24 hours in the future, and replace it some 7-8 hours before it would expire.

It is unclear what the defaults would be for rpkid child CAs (the only other known delegated RPKI CA option), but I believe that they can be configured to check with the parent at an interval determined by the user.

Based on this it should be pretty safe to assume that a CA which has not checked back with the parent for 8 hours is probably inactive for some reason and may be about to have its MFT/CRL go stale/expired as well.

So, the idea then is to have a configurable option to automatically suspend any child CA which has not been seen to do a successful exchange for X hours, default: 8 hours.

The parent CA should withdraw the certificate(s) issued to a suspended child CA, but still allow it to connect. If and when the child CA successfully connects again, then the old certificates should be republished for it.

Note that there is use case for this over simply removing an inactive child CA: if the inactive child comes back and it had been removed, then it can't recover properly.

**Comment by ties** [comment]
Eight hours feels a bit low for this. Does it make sense to set an equal
value here to the default manifest expiration period?

**Comment by timbru** [comment]
It does feel short, but 8 hours is actually aligned with the worst case scenario for mft republishing. Krill will republish 8 hours before a mft would expire.

Arguably we could aim for something like 24 hours instead, but then it would also make sense to change the default republishing strategy for Krill CAs to use e.g. a 36 hour next update and republish 24 hours before expiry. That would result in two publication events per day so the churn is still somewhat okay, and the replay window is not extended by a whole lot.

In any event I think the values should be configurable. Nothing is set in stone.. it may also requiring some measurements and tweaking at an NIR level to fine tune this in the end.

**Comment by ties** [comment]
> It does feel short, but 8 hours is actually aligned with the worst case scenario for mft republishing. Krill will republish 8 hours before a mft would expire.

In that case it's the value I would have picked as well.

I will try to add my prometheus alerts for routinator to the read the docs. A similar set of rules for krill (an alert if it can not communicate with the upstream etc) would also be nice.
