### ISSUE TITLE
Re-enable RIPE NCC Validator 3 in the E2E test?

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#639]
While resolving some issues in the E2E test caused by recent changes in the `dev` branch I ran into a problem with the RIPE NCC Validator 3 whereby it attempts to download the TAL certificate using Rsync but from a HTTPS URI. I have temporarily excluded RIPE NCC Validator 3 from the E2E test but we should consider if we want to fix this issue or given the sunsetting of the RIPE NCC Validator 3 whether we instead want to remove it from the test entirely.

**Comment by ximon18** [comment]
Am going to leave this disabled but not removed. We can always clean up later but maybe by then we instead replace the current e2e test with something else, this isn't worth investing time to clean up right now.

**Comment by timbru** [comment]
Since the ncc validator is end of life I think it can now be removed altogether. It is unlikely to catch regressions not found by other solutions in future, while it may cause issues because it will be unmaintained.

**Comment by timbru** [comment]
but indeed, no rush if it is disabled and not causing issues
