### ISSUE TITLE
Set up end-to-end testing (TA-CA-ROA-validation)

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill#66]
Allows for better functional and regression testing of krill functions. We can use routinator (as a library) to verify that the set of VRPs reflects our expectations under various scenarios (resource allocation/shrink/revocation, keyrolls..)

As a start these tests can be part of the krill project itself. But, in future, we also want to work on a more generic test-framework where various scenarios can be tested using a mesh of implementations for TA/CA - validation - RTR - routers (for interoperability / release testing)

But, first things first.

**Comment by ximon18** [comment]
Potentially covered by #17 although that uses Routinator as a Docker container, not as a library. @timbru ?

**Comment by timbru** [comment]
Yes, using the e2e and containers is just fine for this. #17 was intended to describe just having the test infrastructure, in this one was about having an actual tests. We probably should have had just one issue, but issues are cheap :)
