### ISSUE TITLE
Clean up old keys

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill#728]
Keys are currently not cleaned up if a key roll is completed, or a CA is removed. This could lead to issues when using an HSM with limited space for keys.

Note: check whether `destroy_key` should be idempotent - or errors ignored in case the CA wants to clean up a key which is already removed.

**Comment by ximon18** [comment]
Related: #569

**Comment by ximon18** [comment]
Closing as a duplicate of #106.
