### ISSUE TITLE
Inconsistent krill_admin handling of incorrect -help argument

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#73]
With Krill master branch commit `183f81`:

In some cases `-help` (note the single `-` character) results in the help being shown, e.g.:
```
# krill_admin -s https://localhost:3000/ -t ${KRILL_AUTH_TOKEN} cas -help
krill_admin-cas 
Manage CAs
...
```

In others it results in an error:
```
# krill_admin -s https://localhost:3000/ -t ${KRILL_AUTH_TOKEN} cas roas -help
No valid command given, see --help
```

**Comment by timbru** [comment]
This can't be helped really, it's a property of how 'clap' works. Will document that '--help' should be used :)
