### ISSUE TITLE
Question about hardware backend support

### ISSUE THREAD

**Issue by ionut-arm** [NLnetLabs/krill#730]
Hello!

I discovered your project through the PR on https://github.com/mheese/rust-pkcs11 , found it quite interesting, and wanted to raise a question with you about a potential integration for crypto hardware backend support.

I'm one of the developers/maintainers of [Parsec](https://github.com/parallaxsecond/parsec), a CNCF project intended as an abstraction over hardware cryptographic services (HSMs, TPMs, TEE-based crypto implementations etc). Parsec works as a userspace service which interfaces with the configured hardware and allows client applications to provision and use these capabilities over a local transport mechanism (Unix domain sockets for now) using an abstracted interface (based on [PSA Crypto](https://armmbed.github.io/mbed-crypto/psa/)). The service also offers multitenancy support, currently using Unix Domain Socket credentials (essentially based on Unix user IDs) or [Spiffe](https://spiffe.io/). Access from client applications is done through a client library, for example our [Parsec Rust client](https://docs.rs/parsec-client/*/parsec_client/core/basic_client/struct.BasicClient.html). 

In terms of operation support we have covered a large number of crypto primitives in the service API, however in terms of [backend support](https://parallaxsecond.github.io/parsec-book/parsec_client/operations/service_api_coverage.html) we've focused mostly on asymmetric signing and encryption (+ verification and decryption, of course). For more detailed information you can browse through the rest of the [Parsec Book](https://parallaxsecond.github.io/parsec-book/index.html).

My question, since I don't think I have a strong grasp of your requirements and roadmap, was: do you think there is any room here for an integration between Krill and Parsec?

EDIT: I've discovered your [HSM support for keys project](https://github.com/NLnetLabs/krill/projects/17) :) will skim through!

**Comment by ximon18** [comment]
Hi @ionut-arm,

Thanks for getting in touch and letting us know about the Parsec project, and also for [sharing your experiences](https://github.com/NLnetLabs/krill/pull/727#issuecomment-974881030) with the Rust `pkcs11` crate and the rationale for creating your own `cryptoki` crate.

Regarding requirements and roadmap, the aim was to extend Krill to support PKCS#11 and KMIP based generation of and signing with RSA key pairs.

As to your question, we'll certainly keep Parsec in mind for the future, especially if we get requests from customers to support it, but have no plans to integrate support for Parsec at this time.

Ximon
On behalf of the NLnet Labs Krill team

**Comment by ionut-arm** [comment]
Hi Ximon,

Thanks for the explanation, that makes sense!
