### ISSUE TITLE
[Security] Workflow coverage.yml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by igibek** [NLnetLabs/krill#746]
The workflow coverage.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by ximon18** [comment]
A [number of such issue reports](https://github.com/search?q=The+workflow+coverage.yml+is+referencing+action+actions%2Fcheckout+using+references+v1&type=issues) seem to have been opened across GitHub by a few different users around the same time, referencing this commit in the actions/checkout action dating back to December 2019 which is a bit strange.

Looking at the release notes for the first release of the actions/checkout action after this commit, which is v2.0.0, there is no mention of any security related fixes. Looking at the commit itself it does indeed seem to do an obscure dance to attempt to prevent some sort of credential capture by passing a dummy config value to the Git library and then overwriting the value that the library wrote to its own config file.

We do not appear to be misusing the action nor have I found any CVE related to it, and the issue report seems to be generic and not specifically created to address an issue in our project. The [only other response to these issues at this time](https://github.com/ollpu/tiralabra/issues/2#issuecomment-997510557) was also an indication that information on the vulnerability could not be found and a request for more information. I can only imagine that in some way the Git library used by the v1 version of actions/checkout invokes the `git` process via the command line and passes the authentication token as a command line argument which can end up in process auditing logs.

As actions/checkout v2 is quite mature now and the affected function in actions/checkout v1 no longer seems to exist in v2 implying there has been yet more work done concerning git authentication, I will see if upgrading to actions/checkout v2 works with our project(s).

**Comment by ximon18** [comment]
Note that the coverage workflow is actually disabled anyway and so cannot be an issue at present, but upgrading to actions/checkout v2 still potentially has value.
