### ISSUE TITLE
Build my own root CA

### ISSUE THREAD

**Issue by gitthehit** [NLnetLabs/krill#801]
I read the docs about the Krill, and i wanted to build a RPKI system in my own virtual environment. But it seems i can't create CA if i don't
 connect to a Parent CA. I'd like to know about how to run as a root CA.

**Comment by timbru** [comment]
Hi,

If you just want to do some testing with krill without the need to set up a root CA, then you can set it up under our testbed environment as described in this blog post:

https://blog.nlnetlabs.nl/testing-the-waters-with-krill/

There is no support in Krill to set up a dedicated "production" root CA (Trust Anchor) - at least not yet. But you can set up your own local testbed environement - which includes a TA - if you wish. Please have a look at this blog post where we talk about how we did our own set up of 'testbed.krill.cloud':

https://blog.nlnetlabs.nl/krill-sanctuary/

Hope this helps!

**Comment by gitthehit** [comment]
Thanks，I'll try it.
