### ISSUE TITLE
Query initialisation parameters for Krill pubserver (rrdp/rsync URI)

### ISSUE THREAD

**Issue by wibisono** [NLnetLabs/krill#835]
Hi,

It would be great if we could query the initialization parameters used in the publication server, i.e:
https://krill.docs.nlnetlabs.nl/en/stable/publication-server.html#initialise-publication-server

Perhaps some end point or CLI options to get back the rrdp and rsync URL used.

Cheers,

Adianto

**Comment by timbru** [comment]
done
