### ISSUE TITLE
Package not found on Ubuntu 22.04

### ISSUE THREAD

**Issue by tylerjharden** [NLnetLabs/krill#847]
After following the install guide and adding the GPG key and main repository and updating apt, when I run "apt install krill" I simply get a "Package not found: krill" error.

I have re-attempted this from scratch 3 times, with the same result. Not sure what may be going on here. Even specifying a version does nothing, and the apt policy shows nothing as well.

**Comment by AlexanderBand** [comment]
Hi Tyler, that's correct. We don't support Ubuntu 22.04 yet due to a libssl mismatch. We have PR https://github.com/NLnetLabs/krill/pull/838 open for it, which is looking good. We'll try to merge in time for [Krill 0.10.0](https://github.com/NLnetLabs/krill/projects/19), coming soon.

**Comment by AlexanderBand** [comment]
As our testing went very smoothly, we decided to add the Ubuntu 22.04 package for Krill 0.9.6 to our repository, so you can install Krill today already!  Please run `apt update` and then try to do an `apt install krill` again:

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
root@71b83ce06fc1:/# apt install krill
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  krill
0 upgraded, 1 newly installed, 0 to remove and 8 not upgraded.
Need to get 8877 kB of archives.
After this operation, 36.8 MB of additional disk space will be used.
Get:1 https://packages.nlnetlabs.nl/linux/ubuntu jammy/main amd64 krill amd64 0.9.6-1jammy [8877 kB]
Fetched 8877 kB in 0s (29.6 MB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package krill.
(Reading database ... 5952 files and directories currently installed.)
Preparing to unpack .../krill_0.9.6-1jammy_amd64.deb ...
Unpacking krill (0.9.6-1jammy) ...
Setting up krill (0.9.6-1jammy) ...
```
