### ISSUE TITLE
Do not try to migrate missing ca objects

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill#941]
`CaObjectsMigration::prepare_new_data_for` errors out if a CA has no objects to migrate. It should just be happy that there is no work to do..

**Comment by ximon18** [comment]
Which version of Krill does this affect?

**Comment by timbru** [comment]
This affects upgrades from 0.9.x to 0.10.x or 0.11.x (not released yet) - but only in cases where one added a CA which has no objects: i.e. it has no repository, or no parent, or it does have a parent and repository but it does not have any resource entitlements.

This is a corner case that is unlikely to affect production environments, but it can occur quite easily in test setups where many CAs are added and removed, and what not.
