### ISSUE TITLE
API uses uri and url attribute for certificate URLs

### ISSUE THREAD

**Issue by ties** [NLnetLabs/krill#980]
Hi,

I'm parsing data from the krill api. When building the model I noticed the following inconsistency when parsing the parents of a CA:

`issued_certs` and `signing_cert` have very similar content (the address of the certificate + the base64 content). However one calls the field `uri`, the other `url`. It may be nice to make this consistent at some point [which will break my parser].

**Comment by timbru** [comment]
I agree that this is inconsistent and ugly. Unfortunately there are more places in the API where we have some inconsistencies that were introduces as the API grew organically..

Part of me wants to do an overhaul of the API to make it all consistent. But a bigger part of me wants to avoid introducing breaking changes for aesthetic reasons only as it will affect not just your parser, but any parser out there that current users have created.

**Comment by ties** [comment]
I feel the same way about it. For me the best moment to make it more consistent is when an api part is changing anyway.

To me these changes are not worth an API version.

**Comment by timbru** [comment]
ok, I will close this for now then.
