### ISSUE TITLE
Krill service_uri support and wildcard subdomains

### ISSUE THREAD

**Issue by cli0** [NLnetLabs/krill#986]
Is there a way to configure the service URI in Krill to be a domain with a wildcard subdomain, for example *.rpki.com? Or does it only accept static domains?

**Comment by timbru** [comment]
The service uri is used for the 'service_uri' attribute in RFC 8183 Parent Response XML (if your CAs act as parents) and Repository Response XML (if you run a Publication Server). Wild card domains are not supported there (clients would not know where to connect).

That said.. the domain is not used in the protocol (except for TLS verifications which you would have to tweak) - so if you want to use different domains for different clients for some reason then you could simply replace the hostname in the XML before giving the response to client. And then have a proxy handle the domains as you like - as long as they end up on the same back-end Krill server. Note that multiple active node setup is not yet supported.
